# for AZURE pipeline
name: BMI test trigger
# 啟動的條件
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
# 啟動之後需要執行的工作
jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 階層式工作執行, 建議根據需要執行工作做排序
      - name: check-out
        uses: actions/checkout@v2
      # 保持 docker image 與 external github 同步
      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/jeffrey-yc/dotNetBMI:latest
# Use WebAPPService
app: user-authentication 
port: 6000
version: 2
